[project]
name = "pyarrow"
version = "7.0.0"
description="Python arrow library pyodide port"
requires-python = ">=3.10"

[build-system]
requires = ["setuptools ~= 64.0", "Cython >= 0.29.0"]
build-backend = "setuptools.build_meta"
