name: Build for pyodide

on:
  push:
    branches:
      - main
    tags: 
      - "v*.*.*"
  pull_request:
  workflow_dispatch:

jobs:
  build:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        - uses: actions/setup-python@v4
          with:
             python-version: 3.10.2
        - uses: mymindstorm/setup-emsdk@v11
          with:
             version: 3.1.14
        - name: Verify emsdk
          run: emcc -v
        - run: pip install pyodide-build==0.21.0
        - run: CMAKE_MAKE_PROGRAM=make pyodide build
        - uses: actions/upload-artifact@v3
          with:
             name: pyarrow_wheel
             path: dist
  make_release_on_new_tag:
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    needs: build    
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: pyarrow_wheel
          path: pyarrow_wheel
      - name: Zip folders
        run:  tar -czvf pyarrow_wheel.tgz pyarrow_wheel 
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            pyarrow_wheel.tgz
